#!/usr/bin/env bash
#
# pctl: a simple tool to manage your projects
#
# Author: @trimclain
# License: GPL-3.0

# shellcheck disable=SC2155,SC2164
# Disabled:
# "Declare and assign separately to avoid masking return values":
#  https://www.shellcheck.net/wiki/SC2155
# "Use 'pushd ... || exit' or 'pushd ... || exit' in case pushd fails":
#  https://www.shellcheck.net/wiki/SC2164

readonly VERSION="v0.2.0"

readonly GREEN='\e[0;32m'
readonly BLUE='\e[0;34m'
readonly RED='\e[0;31m'
readonly PURPLE="\e[0;35m"
readonly RESET='\e[0m'

ensure_installed() {
    if ! command -v "$1" > /dev/null; then
        echo "Error: $1 not found"
        exit 1
    fi
}

readonly MESSAGE_LENGTH=60
readonly LEFT_LENGTH=25

##################################################################
# Idea:
#                         MESSAGE_LENGTH
#                               |
# (-------------------------------------------------------------)
# -------------------------> pctl <-----------------------------
# (------------------------)
#            |
#      LEFT_LENGTH
#
# Produce the following:
# -------------------------> <text> <-----------------------------
##################################################################
center_text() {
    local text="$1"
    local text_length=${#text}
    local right_length=$((MESSAGE_LENGTH - 2 - text_length - LEFT_LENGTH))

    local left=$(printf "%-${LEFT_LENGTH}s" "" | tr ' ' '-')
    local right=$(printf "%-${right_length}s" "" | tr ' ' '-')
    printf "%s> ${PURPLE}%s${GREEN} <%s" "$left" "$text" "$right"
}

#######################################
# Delete the last n lines in the terminal.
# Arguments:
#   n: (Optional) Number of lines; default: 1
#######################################
delete_last_lines() {
    local n=${1:-1}

    while ((n-- > 0)); do
        printf '\r'      # Move to the start of the current line.
        printf '\033[2K' # Clear the entire current line.
        printf '\033[1A' # Move cursor up by one line.
    done

    # After the loop, we are sitting on the line above the top deleted line.
    # Move to column 1 and clear that line too, so the full block is gone.
    printf '\r'
    printf '\033[2K'
}

#######################################
# Show git status of all projects in the list.
# Globals:
#   GREEN
#   RESET
#   PROJECTLIST
#######################################
show_status() {
    while IFS=, read -r project _; do
        local project_name="${project##*/}"
        local formatted_line=$(center_text "$project_name")

        if [ -d "$project/.git" ]; then
            echo -e "${GREEN}${formatted_line}${RESET}"

            if [[ -n $(git -C "$project" status --porcelain) ]]; then
                git -C "$project" status
            else
                echo "Nothing to commit"
            fi
        fi
    done < "$PROJECTLIST"
}

#######################################
# Run git pull for all projects in the list.
# Globals:
#   GREEN
#   RESET
#   PROJECTLIST
#######################################
pull_updates() {
    local tmp_dir=$(mktemp -d)
    trap 'rm -rf -- "$tmp_dir"' EXIT

    local installed_projects=()
    local log_files=()

    while IFS=, read -r project _; do
        local project_name="${project##*/}"
        local formatted_line=$(center_text "$project_name")

        if [ -d "$project/.git" ]; then

            local log_file=$(mktemp "$tmp_dir/${project_name}_XXXXXX.log")

            installed_projects+=("$formatted_line")
            log_files+=("$log_file")

            echo -e "${GREEN}${formatted_line}${RESET}"

            git -C "$project" pull > "$log_file" 2>&1 &
        fi
    done < "$PROJECTLIST"
    wait

    local len=${#installed_projects[@]}
    delete_last_lines "$len"

    for i in "${!installed_projects[@]}"; do
        echo -e "${GREEN}${installed_projects[$i]}${RESET}"
        cat "${log_files[$i]}"
    done
}

#######################################
# Add CWD to the project list.
# Globals:
#   BLUE
#   GREEN
#   RESET
#   CURRENT_USER
#   PROJECTLIST
# Arguments:
#   gh_repo_owner: (Optional) Owner of the repo on GitHub
#######################################
add_project() {
    local project=$(pwd)
    local project_name="${project##*/}"

    if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
        echo -e "Project ${BLUE}$project_name${RESET} is not a git repository ${RED}${RESET}"
        exit 1
    fi

    if grep -qF "$project" "$PROJECTLIST"; then
        echo -e "Project ${BLUE}$project_name${RESET} is already in the list ${RED}${RESET}"
    else
        local gh_repo_owner
        if [[ -n "$1" ]]; then
            gh_repo_owner="$1"
        else
            echo -en "Enter ${BLUE}github repo owner${RESET} (default: $CURRENT_USER): "
            read -r gh_repo_owner
            gh_repo_owner=${gh_repo_owner:-$CURRENT_USER}
        fi
        echo "$project,$gh_repo_owner" >> "$PROJECTLIST"
        echo -en "Adding ${BLUE}$project_name${RESET} with owner ${BLUE}$gh_repo_owner${RESET} to the list "
        echo -e "${GREEN}✔${RESET}"
    fi
}

#######################################
# Clone the project chosen from the list.
# Prefer SSH but fallback to HTTPS.
# Globals:
#   BLUE
#   GREEN
#   RESET
#   PROJECTLIST
# Arguments:
#   gh_repo_owner: (Optional) Owner of the repo on GitHub
#######################################
get_project() {
    # filter out installed projects
    local project=$(while IFS=, read -r line _; do
        if [ ! -d "$line" ]; then
            echo "$line"
        fi
    done < "$PROJECTLIST" | fzf --cycle --bind 'tab:toggle-up,btab:toggle-down')

    if [[ -z $project ]]; then
        exit 0
    fi

    local project_name="${project##*/}"
    local project_dir="${project%/*}"
    local gh_repo_owner=$(awk -F, -v selected="$project" '$1 == selected {print $2; exit}' "$PROJECTLIST")

    if [[ ! -d $project_dir ]]; then
        mkdir -p "$project_dir"
    fi

    echo -en "Cloning ${BLUE}$project_name${RESET} "

    if GIT_SSH_COMMAND="ssh -o BatchMode=yes -o ConnectTimeout=1" \
        git clone --quiet "git@github.com:$gh_repo_owner/$project_name" "$project" 2> /dev/null; then
        :
    else
        git clone --quiet "https://github.com/$gh_repo_owner/$project_name" "$project"
    fi

    echo -e "${GREEN}✔${RESET}"
}

#######################################
# Open the project chosen from the list in tmux.
# Globals:
#   PROJECTLIST
# Arguments:
#   selected: (Optional) Name of the project to open
#######################################
open_in_tmux() {
    local selected
    if [[ -n "$1" ]]; then
        selected=$1
    else
        selected=$(
            while IFS=, read -r line _; do
                if [[ -d "$line" ]]; then
                    echo "$line"
                fi
            done < "$PROJECTLIST" |
                sed "s|$HOME/\(.*\)|\1|" |
                fzf --cycle --bind 'tab:toggle-up,btab:toggle-down'
        )
    fi

    if [[ -z $selected ]]; then
        exit 0
    fi

    # make selected back to fullpath
    if [[ ! $selected == $HOME/* ]]; then
        selected=$HOME/$selected
    fi
    local selected_name=$(basename "$selected" | tr . _)

    # Tmux not running or detached:
    # the -A flag makes new-session behave like attach-session if session-name
    # already exists
    if [[ -z $TMUX ]]; then
        tmux new-session -A -s "$selected_name" -c "$selected"
        exit 0
    fi

    # the -d flag makes tmux detach from a session and then creates new one
    # with the name given after -s flag
    if ! tmux has-session -t="$selected_name" 2> /dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi

    tmux switch-client -t "$selected_name"
}

display_help() {
    cat << EOF
Usage:
  pctl [command]

COMMANDS:
  h, help               Show this help message
  v, version            Print pctl version
  s, status             Show the status of all projects
  p, pull               Pull updates in all projects
  g, get                Clone a project from github
  a, add [owner]        Add current project to the list (optional: pass github repo owner)
  o, open [project]     Open a project in a new tmux session (optional: pass project name)
EOF
}

main() {
    ensure_installed fzf
    ensure_installed tmux

    readonly CURRENT_USER=$(whoami)
    readonly PCTL_SHARE="$HOME/.local/share/pctl"

    # INFO:
    # PROJECTLIST is a csv with following columns:
    #   - project location full path
    #   - github repo owner (default: $USER)
    if [[ -z $PROJECTLIST ]]; then
        readonly PROJECTLIST="$PCTL_SHARE/projectlist"
        if [[ ! -f $PROJECTLIST ]]; then
            mkdir -p "$PCTL_SHARE"
            touch "$PROJECTLIST"
        fi
    fi

    if [[ $# -eq 0 ]]; then
        display_help
        exit 0
    fi
    local cmd="$1"
    shift
    case $cmd in
        "help" | "h" | "--help" | "-h") display_help && exit 0 ;;
        "version" | "v" | "--version" | "-v" | "-V") echo "pctl $VERSION" && exit 0 ;;
        "status" | "s") show_status && exit 0 ;;
        "pull" | "p") pull_updates && exit 0 ;;
        "get" | "g") get_project && exit 0 ;;
        "add" | "a") add_project "$2" && exit 0 ;;
        "open" | "o") open_in_tmux "$2" && exit 0 ;;
        *) echo "Unknown command: $cmd" && exit 1 ;;
    esac
}

main "$@"
